// Mocks generated by Mockito 5.4.4 from annotations
// in study_chill_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/material.dart' as _i8;
import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:study_chill_app/core/constants/app_constants.dart' as _i6;
import 'package:study_chill_app/features/analytics/analytics_state.dart' as _i7;
import 'package:study_chill_app/features/settings/settings_state.dart' as _i4;
import 'package:study_chill_app/features/tasks/task_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTask_1 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettingsState_2 extends _i1.SmartFake implements _i4.SettingsState {
  _FakeSettingsState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set box(_i2.Box<_i3.Task>? box) => super.noSuchMethod(
        Invocation.setter(
          #box,
          box,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Box<_i3.Task> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<_i3.Task>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<_i3.Task>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.Task> getAll({
    String? category,
    bool? completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #category: category,
            #completed: completed,
          },
        ),
        returnValue: <_i3.Task>[],
      ) as List<_i3.Task>);

  @override
  _i5.Stream<List<_i3.Task>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i5.Stream<List<_i3.Task>>.empty(),
      ) as _i5.Stream<List<_i3.Task>>);

  @override
  _i3.Task addTask({
    required String? title,
    required _i6.TaskPriority? priority,
    int? targetPomodoros = 1,
    String? category = r'Général',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [],
          {
            #title: title,
            #priority: priority,
            #targetPomodoros: targetPomodoros,
            #category: category,
          },
        ),
        returnValue: _FakeTask_1(
          this,
          Invocation.method(
            #addTask,
            [],
            {
              #title: title,
              #priority: priority,
              #targetPomodoros: targetPomodoros,
              #category: category,
            },
          ),
        ),
      ) as _i3.Task);

  @override
  _i5.Future<void> updateTask(_i3.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleTask,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> incrementPomodoro(String? id) => (super.noSuchMethod(
        Invocation.method(
          #incrementPomodoro,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearCompleted() => (super.noSuchMethod(
        Invocation.method(
          #clearCompleted,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i7.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i7.SessionRecord> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBox_0<_i7.SessionRecord>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.Box<_i7.SessionRecord>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i7.SessionRecord> getAll({
    DateTime? start,
    DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {
            #start: start,
            #end: end,
          },
        ),
        returnValue: <_i7.SessionRecord>[],
      ) as List<_i7.SessionRecord>);

  @override
  _i5.Stream<List<_i7.SessionRecord>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.SessionRecord>>.empty(),
      ) as _i5.Stream<List<_i7.SessionRecord>>);

  @override
  _i5.Future<void> addSession(_i7.SessionRecord? session) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSession,
          [session],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i4.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i4.SettingsState load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _FakeSettingsState_2(
          this,
          Invocation.method(
            #load,
            [],
          ),
        ),
      ) as _i4.SettingsState);

  @override
  _i5.Future<void> save(_i4.SettingsState? state) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [state],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLocale(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLocale,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setThemeMode(_i8.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setWorkDuration(int? minutes) => (super.noSuchMethod(
        Invocation.method(
          #setWorkDuration,
          [minutes],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMasterVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setMasterVolume,
          [volume],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
